default:
  ingatlanCom:
    pairs: [ [
          "css", "body > div.site__content > div.card.listing > div.listing-left > div.listing-parameters > div.parameter.parameter-area-size > span.parameter-title",
          "css", "body > div.site__content > div.card.listing > div.listing-left > div.listing-parameters > div.parameter.parameter-area-size > span.parameter-value"
        ], [
          "css", "body > div.site__content > div.card.listing > div.listing-left > div.listing-parameters > div.parameter.parameter-room > span.parameter-title",
          "css", "body > div.site__content > div.card.listing > div.listing-left > div.listing-parameters > div.parameter.parameter-room > span.parameter-value"
        ], [
          "text", "Ãr",
          "css", "div.site__content > div.card.listing > div.listing-left > div.listing-parameters > div.parameter.parameter-price > span.parameter-value"
        ], [
          "format_css", "div.paramterers > table > tr:nth-child({0}) > td:nth-child(1)",
          "format_css", "div.paramterers > table > tr:nth-child({0}) > td:nth-child(2)"
        ] ]
